import os
import requests
import streamlit as st

API_URL = os.getenv("API_URL", "http://localhost:8000")

def upload_file(uploaded_file) -> dict:
    """
    Upload a PDF file to the backend API for processing.

    Parameters
    ----------
    uploaded_file : streamlit.runtime.uploaded_file_manager.UploadedFile
        The uploaded PDF file object generated by Streamlit's file_uploader.

    Returns
    -------
    dict
        A dictionary containing the success message from the API.

    Raises
    ------
    requests.exceptions.HTTPError
        If the HTTP request returns an unsuccessful status code (e.g., 400, 409, 500).
    """
    files = {"file": (uploaded_file.name, uploaded_file.getvalue(), "application/pdf")}
    response = requests.post(f"{API_URL}/upload", files=files)
    response.raise_for_status()
    return response.json()

def get_files() -> list:
    """
    Retrieve a list of available PDF files from the backend API.

    Returns
    -------
    list
        A list of strings representing the filenames currently stored on the server.

    Raises
    ------
    requests.exceptions.HTTPError
        If the HTTP request returns an unsuccessful status code.
    """
    response = requests.get(f"{API_URL}/files")
    response.raise_for_status()
    return response.json().get("files", [])

def delete_file(filename: str) -> None:
    """
    Request the backend API to delete a specific PDF file and its vector embeddings.

    Parameters
    ----------
    filename : str
        The exact name of the file to be deleted.

    Returns
    -------
    None

    Raises
    ------
    requests.exceptions.HTTPError
        If the HTTP request returns an unsuccessful status code.
    """
    response = requests.delete(f"{API_URL}/files/{filename}")
    response.raise_for_status()

def ask_question(question: str) -> str:
    """
    Send a user query to the backend API and retrieve the RAG-generated answer.

    Parameters
    ----------
    question : str
        The query/question asked by the user regarding the uploaded documents.

    Returns
    -------
    str
        The textual answer generated by the LLM based on the document context.

    Raises
    ------
    requests.exceptions.HTTPError
        If the HTTP request returns an unsuccessful status code.
    """
    response = requests.post(f"{API_URL}/chat", json={"question": question})
    response.raise_for_status()
    return response.json()["answer"]